/*
5. Crie uma aplicação que apresente um menu de botões com todos os exemplos de eventos 
(do 1 ao 5) citados na aula 14_1, similar à imagem abaixo. Ao clicar no botão referente 
ao exemplo escolhido, chamar a aplicação para ser executada.
*/

package Exercícios.Exercício5;

public class Exercício5 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Exercício5() {
        initComponents();
        setLocation(500, 200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ActionListener = new javax.swing.JButton();
        ItemListener = new javax.swing.JButton();
        KeyPressed = new javax.swing.JButton();
        MouseListener = new javax.swing.JButton();
        BotãoLimpa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("O que você deseja?");

        ActionListener.setText("Exemplo com Action Listener");
        ActionListener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionListenerActionPerformed(evt);
            }
        });

        ItemListener.setText("Exemplo com Item Listener");
        ItemListener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemListenerActionPerformed(evt);
            }
        });

        KeyPressed.setText("Exemplo com Key Pressed");
        KeyPressed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeyPressedActionPerformed(evt);
            }
        });

        MouseListener.setText("Exemplo com Mouse Listener");
        MouseListener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MouseListenerActionPerformed(evt);
            }
        });

        BotãoLimpa.setText("Exemplo com Botão Limpa");
        BotãoLimpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoLimpaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ActionListener, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MouseListener, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ItemListener, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(KeyPressed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotãoLimpa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(ActionListener)
                .addGap(18, 18, 18)
                .addComponent(ItemListener)
                .addGap(18, 18, 18)
                .addComponent(KeyPressed)
                .addGap(18, 18, 18)
                .addComponent(MouseListener)
                .addGap(18, 18, 18)
                .addComponent(BotãoLimpa)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotãoLimpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoLimpaActionPerformed
        EventoLimpa objeto = new EventoLimpa();
        objeto.executa();
    }//GEN-LAST:event_BotãoLimpaActionPerformed

    private void ActionListenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionListenerActionPerformed
        EventoAction objeto = new EventoAction();
        objeto.executa();
    }//GEN-LAST:event_ActionListenerActionPerformed

    private void ItemListenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemListenerActionPerformed
        EventoItem objeto = new EventoItem();
        objeto.executa();
    }//GEN-LAST:event_ItemListenerActionPerformed

    private void KeyPressedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeyPressedActionPerformed
        EventoKey objeto = new EventoKey();
        objeto.executa();
    }//GEN-LAST:event_KeyPressedActionPerformed

    private void MouseListenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MouseListenerActionPerformed
        EventoMouse objeto = new EventoMouse();
        objeto.executa();
    }//GEN-LAST:event_MouseListenerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercício5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercício5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercício5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercício5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercício5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActionListener;
    private javax.swing.JButton BotãoLimpa;
    private javax.swing.JButton ItemListener;
    private javax.swing.JButton KeyPressed;
    private javax.swing.JButton MouseListener;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
